### ISSUE TITLE
dead ref

### ISSUE THREAD

**Issue by shendel** [swaponline/back#1]
https://github.com/swaponline/back/blob/3c8f2d67b0fdccb8e994b2f72f91c01ae3681284/swap.io-agent/src/auth/decodeAccessToken.go#L4

судя по пулл-реквестам и списку ишью - мертвая либа

**Comment by shendel** [comment]
@DmitryLebedevDev

**Comment by DmitryLebedevDev** [comment]
смотрел сайт https://jwt.io/ тогда она еще была в списке
переписал на более свежую https://github.com/lestrrat-go/jwx/tree/main/jwt(взята из списка по go https://jwt.io/)
